[workspace]
members = []
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Vitalii Lukyanov <tukanoid@outlook.com>"]

[package]
name = "rbar"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
iced = { version = "0.13.1", features = ["advanced", "tokio", "wgpu"] }
iced_layershell = "0.13.2"
iced_aw = "0.11.0"

smithay-client-toolkit = "0.19.2"

tokio = { version = "1.43.0", features = ["rt-multi-thread"] }

clap = { version = "4.5.28", features = ["derive"] }

directories = "5.0.1"
chrono = "0.4.39"
uuid = { version = "1.13.1", features = ["v4"] }
itertools = "0.14.0"

serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
nickel-lang-core = { version = "0.10.0", default-features = false }

tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

miette = { version = "7.5.0", features = ["fancy", "syntect-highlighter"] }
thiserror = "2.0.11"

smart-default = "0.7.1"
derive_more = { version = "1.0.0", features = [
  "debug",
  "deref",
  "deref_mut",
  "from",
  "into",
] }

paste = "1.0.15"
pipewire = { version = "0.8.0", features = ["v0_3_77"] }
